### PR TITLE
Fix setting pluginName in Sprite.convertTo2d

### LINKED ISSUE #59: Broken convertSubtreeTo2d in pixi v5
Hi,

I am trying to use pixi-projection (0.3.5) with pixi v5 (5.1.5). I've noticed that convertSubtreeTo2d does not work in such a configuration. Here you have a broken sandbox.

https://codesandbox.io/s/broken-pixi-projection-convertsubtreeto2d-ex2pk

Error:

```
Uncaught TypeError: Cannot read property 'start' of undefined
    at BatchSystem.setObjectRenderer (core.js:5552)
    at Sprite._render (sprite.js:394)
    at Sprite.render (display.js:1626)
    at Container.render (display.js:1631)
    at Container.render (display.js:1631)
    at Renderer.render (core.js:11266)
    at Application.render (app.js:77)
    at TickerListener.emit (ticker.js:138)
    at Ticker.update (ticker.js:677)
    at Ticker._tick (ticker.js:376)
```

Changing PIXI.Sprite to PIXI.projection.Sprite2d fixes the problem but I think that this is not the way how convertSubtreeTo2d should work.

You can just change dependencies to pixi 4.8.8 and pixi-projection 0.2.8 to see that example work as intended.

### PR DESCRIPTION
**Pull request by kozickikarol**
+ Bumped pixi.js version to 5.2.1
In package.json there was "pixi.js": "~5.2.0" so npm downloads the newest 5.2.x version (right now it is 5.2.1). Unfortunately 5.2.1 brings lots of changes, one of them are changes in Point.set method. That's why I needed to change Point3d.set as well.

+ Fixed Point3d.set method (there were errors during build)

+ Fixed setting pluginName in Sprite.convertTo2d (it fixes #59)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I fixed 1 and 2. Please leave  only convertTo2d , without changes in build - i can run `yarn build` myself.

**Comment by ivanpopelyshev** [comment]
Actually, wait, i'll just do it myself :) EVerything is ok

**Comment by ivanpopelyshev** [comment]
OK, 0.3.9 published. Thank you, its important for me that I'm not the only one who's maintaining this repo.

**Comment by kozickikarol** [comment]
Are you going to release new version?

**Comment by ivanpopelyshev** [comment]
Already

**Pull request closed without merging**
