### PR TITLE
Refactor codebase, move to Rollup-based build, api-extractor to automate typings

### PR DESCRIPTION
**Pull request by ShukantPal**

### CODE REVIEW

**Comment by SukantPal** [comment]
The git diffs aren't a good representation of the changes here 🤔

**Comment by SukantPal** [comment]
@Ivan Ping!

**Comment by SukantPal** [comment]
@ivan Ping!

**Comment by ivanpopelyshev** [comment]
Solve that first ----> https://github.com/pixijs/pixi-tilemap/issues/97#issuecomment-685143850 , once we have everything on tilemap, we'll move it to other modules at the same time.

**Comment by bigtimebuddy** [comment]
This seems out of date now, closing. Will upgrade to api-extractor without moving to pnpm

**Comment by ShukantPal** [comment]
Thanks!

**Pull request closed without merging**
